In [69]:
import pandas as pd
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

In [70]:
d16=pd.read_csv('raw_data/2016-17.csv').set_index('full_name')
d17=pd.read_csv('raw_data/2017-18.csv').set_index('full_name')

In [71]:
#Eliminating all players that dint play in both years 
#sorting alphabetically

for n in d16.index:
    if n not in d17.index:
        d16.drop(n,0,inplace=True)
        
for n in d17.index:
    if n not in d16.index:
        d17.drop(n,0,inplace=True)
        
        

        
d16.sort_values('full_name',inplace=True)
d17.sort_values('full_name',inplace=True)

d16.reset_index(inplace=True)
d17.reset_index(inplace=True)

In [72]:
labels=d17['total_points'].to_numpy()
i=0
while i<len(labels):
    if labels[i]<110:
        labels[i]=0
    else:
        labels[i]=1
    i+=1

In [73]:
labels

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0])

In [74]:
names=d16['full_name'].to_numpy()

In [75]:
data=d16.drop('full_name',1).to_numpy()

In [76]:
data

array([[  0. ,   2. ,  60. , ...,   1. ,   2. ,   0.3],
       [  0. ,   1. ,  22. , ...,   0. ,   0. ,   0.2],
       [  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
       ...,
       [  4. ,   4. ,  91. , ...,   0. ,   7. ,   1.1],
       [  2. ,   0. ,  57. , ...,   0. ,   2. ,   0.6],
       [ 17. ,   7. , 163. , ...,   0. ,   7. ,  22.8]])

In [77]:
train_data=data[:350]

In [78]:
train_labels=labels[:350]

In [79]:
test_data=data[350:]

In [80]:
test_labels=labels[350:]

In [81]:
model = KNeighborsClassifier(n_neighbors=5)

In [82]:
model.fit(train_data, train_labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [83]:
predictions = model.predict(test_data)

In [84]:
results=pd.DataFrame()

In [85]:
results['name']=names[350:]

In [86]:
results['actual']=test_labels
results['predicted']=predictions

In [90]:
results

                       name  actual  predicted
0          Sofiane Feghouli       0          0
1             Stefano Okaka       0          0
2           Stephen Ireland       0          0
3          Stephen Kingsley       0          0
4              Stephen Ward       0          0
5                Steve Cook       0          0
6           Steven Berghuis       0          0
7              Steven Davis       0          0
8             Steven Defour       0          0
9             Stuart Taylor       0          0
10            Sullay Kaikai       0          0
11            Sung-yueng Ki       0          0
12             Theo Walcott       0          0
13         Thibaut Courtois       1          1
14           Thomas Edwards       0          0
15      Timothy Fosu-Mensah       0          0
16        Toby Alderweireld       0          0
17              Tom Carroll       0          0
18            Tom Cleverley       0          0
19               Tom Davies       0          0
20               Tom Heaton       0          0
21   Trent Alexander-Arnold       0          0
22              Troy Deeney       0          1
23             Tyrone Mings       0          0
24            Valon Behrami       0          0
25             Victor Moses       1          0
26           Victor Wanyama       0          0
27          Vincent Janssen       0          0
28          Vincent Kompany       0          0
29          Virgil van Dijk       0          0
30          Wayne Hennessey       0          0
31             Wayne Rooney       0          0
32          Wayne Routledge       0          0
33               Wes Morgan       0          0
34            Wilfred Ndidi       0          0
35            Wilfried Bony       0          0
36            Wilfried Zaha       1          0
37  Willian Borges Da Silva       1          0
38          Willy Caballero       0          0
39             Winston Reid       0          0
40          Xherdan Shaqiri       1          0
41          Yannick Bolasie       0          0
42         Yohan Benalouane       0          0
43             Yohan Cabaye       0          0
44            Younes Kaboul       0          0
45       Zlatan Ibrahimovic       0          1

In [88]:
perc= sum(predictions == test_labels)/len(test_labels)

In [97]:
results

                       name  actual  predicted
0          Sofiane Feghouli       0          0
1             Stefano Okaka       0          0
2           Stephen Ireland       0          0
3          Stephen Kingsley       0          0
4              Stephen Ward       0          0
5                Steve Cook       0          0
6           Steven Berghuis       0          0
7              Steven Davis       0          0
8             Steven Defour       0          0
9             Stuart Taylor       0          0
10            Sullay Kaikai       0          0
11            Sung-yueng Ki       0          0
12             Theo Walcott       0          0
13         Thibaut Courtois       1          1
14           Thomas Edwards       0          0
15      Timothy Fosu-Mensah       0          0
16        Toby Alderweireld       0          0
17              Tom Carroll       0          0
18            Tom Cleverley       0          0
19               Tom Davies       0          0
20               Tom Heaton       0          0
21   Trent Alexander-Arnold       0          0
22              Troy Deeney       0          1
23             Tyrone Mings       0          0
24            Valon Behrami       0          0
25             Victor Moses       1          0
26           Victor Wanyama       0          0
27          Vincent Janssen       0          0
28          Vincent Kompany       0          0
29          Virgil van Dijk       0          0
30          Wayne Hennessey       0          0
31             Wayne Rooney       0          0
32          Wayne Routledge       0          0
33               Wes Morgan       0          0
34            Wilfred Ndidi       0          0
35            Wilfried Bony       0          0
36            Wilfried Zaha       1          0
37  Willian Borges Da Silva       1          0
38          Willy Caballero       0          0
39             Winston Reid       0          0
40          Xherdan Shaqiri       1          0
41          Yannick Bolasie       0          0
42         Yohan Benalouane       0          0
43             Yohan Cabaye       0          0
44            Younes Kaboul       0          0
45       Zlatan Ibrahimovic       0          1